In [132]:
import pickle
import numpy as np

## Opening each model trained and assigning names

In [133]:
model = pickle.load(open('models/model.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))

### Assumed User input

0 = pclass
1 = sibsp
2 = parch
3 = fare
4 = age
5 = embarked
6 = embarked
7 = sex

In [134]:
input = np.array([3.0,0.0,0.0,12.0,28,'S','male'], dtype=object).reshape(1,7) #coz without it shape = (6,) and we want (6,1)

In [135]:
input.shape

(1, 7)

In [136]:
input_sex = ohe_sex.transform(input[:,-1].reshape(1,1)) 

C:\Users\luqma\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [137]:
input_sex

array([[1]])

In [138]:
input_embarked = ohe_embarked.transform(input[:,-2].reshape(1,1))

In [139]:
input_embarked

array([[0, 1]])

## add all healthy cols to one df

In [140]:
input_healthy = input[:,0:4]

In [141]:
input_healthy.reshape(4,)

array([3.0, 0.0, 0.0, 12.0], dtype=object)

In [142]:
input_age = input[:,4] #make age col 

In [143]:
input_age

array([28], dtype=object)

## Concatenate everything to gether 

In [144]:
### Before concatenating confirm if all are in same dimension

In [145]:
print(input_healthy.shape)
print(input_age.shape)
print(input_embarked.shape)
print(input_sex.shape)

(1, 4)
(1,)
(1, 2)
(1, 1)


In [146]:
input_age = input_age.reshape(1,1) #now its matching dimen with others

In [147]:
input_transformed = np.concatenate((input_healthy,input_age,input_embarked,input_sex),axis=1)

In [148]:
model.predict(input_transformed)

array([0])

### testing by inputting data directly

In [150]:
model.predict(np.array([3.0,0.0,0.0,30.000,22.000000,0.0,1.0,1.0]).reshape(1,8))

array([0])

# END ---